#  注意，yml 文件是两个空格进行缩进，而不是 Tab

spring:
  datasource:
    url: jdbc:mysql://tcloud.zhangjin.tk:13306/BOOT?characterEncoding=utf8
    username: boot
    password: boot
  jpa:
    hibernate:
      # create: 启动时删除上一次生成的表，并根据实体类生成表，表中的数据会被清空
      # create-drop：启动时根据实体类生成表，sessionFactory 关闭时表会被删除
      # update: 启动时会根据实体生成表，当实体表属性变动的时候，表结构也会更新，在初期开发阶段使用此选项
      # validate: 启动时验证实体类和数据表是否一致，在我们数据结构稳定时采用此选项
      # none: 不采取任何措施
      ddl-auto: update
    # 用来设置 hibernate 操作的时候在控制台显示其真实的 sql 语句
    show-sql: true
  jackson:
    # 让控制台输出的 json 字符串格式更美观
    serialization: true

info:
  name:
    张进
  age:
    31
  city:
    WuHan



